'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const { readiness, rankingReadiness, isExecutableHttpEndpoint, canonicalProviderIdentity, isFreshLiveQuote } = require('../lib/evidence-readiness');

const base = { provider: 'Provider A', endpoint: 'https://provider.test/search', evidenceSources: [{ type: 'provider', url: 'https://provider.test' }], listedPriceUsd: 0.01 };
const NOW = Date.parse('2026-08-28T02:49:38Z');

test('valid constrained fresh quote makes first paid benchmark ready without prior payment', () => { const result = readiness({ ...base, liveQuoteObserved: true, liveQuoteObservedAt: '2026-08-28T02:45:00Z', liveQuotePolicyCompliant: true, paidExecutionObserved: false }, { now: NOW }); assert.equal(result.preflightReady, true); assert.equal(result.liveQuoteFresh, true); assert.equal(result.quoteVerified, true); assert.equal(result.paidBenchmarkReady, true); assert.equal(result.paidExecutionObserved, false); });
test('resolved endpoint without live quote is not paid benchmark ready', () => { const result = readiness({ ...base, liveQuoteObserved: false }, { now: NOW }); assert.equal(result.preflightReady, true); assert.equal(result.paidBenchmarkReady, false); });
test('stale live quote fails closed even when policy compliant', () => { const result = readiness({ ...base, liveQuoteObserved: true, liveQuoteObservedAt: '2026-08-28T02:20:00Z', liveQuotePolicyCompliant: true }, { now: NOW }); assert.equal(result.liveQuoteFresh, false); assert.equal(result.quoteVerified, false); assert.equal(result.paidBenchmarkReady, false); });
test('live quote without timestamp fails closed', () => { const result = readiness({ ...base, liveQuoteObserved: true, liveQuotePolicyCompliant: true }, { now: NOW }); assert.equal(result.liveQuoteFresh, false); assert.equal(result.paidBenchmarkReady, false); });
test('future-dated live quote fails closed', () => { assert.equal(isFreshLiveQuote({ liveQuoteObserved: true, liveQuoteObservedAt: '2026-08-28T02:50:00Z' }, { now: NOW }), false); });
test('null listed price is not observed or source-backed', () => { const result = readiness({ ...base, listedPriceUsd: null }); assert.equal(result.priceObserved, false); assert.equal(result.sourceBackedPrice, false); });
test('empty listed price is not observed or source-backed', () => { const result = readiness({ ...base, listedPriceUsd: '' }); assert.equal(result.priceObserved, false); assert.equal(result.sourceBackedPrice, false); });
test('paid execution without deterministic score cannot make ranking ready', () => { const ranking = rankingReadiness([{ ...base, paidExecutionObserved: true, outcomeScored: false, providerCanonicalKey: 'provider.test|0xaaa' }]); assert.equal(ranking.rankingReady, false); });
test('one scored canonical provider is not a ranking', () => { const ranking = rankingReadiness([{ ...base, paidExecutionObserved: true, outcomeScored: true, benchmarkFingerprint: 'fp-1', providerCanonicalKey: 'provider.test|0xaaa' }]); assert.equal(ranking.rankingReady, false); });
test('two canonically distinct scored providers under same fingerprint make ranking ready', () => { const ranking = rankingReadiness([{ ...base, provider: 'A', paidExecutionObserved: true, outcomeScored: true, benchmarkFingerprint: 'fp-1', providerCanonicalKey: 'a.test|0xaaa' }, { ...base, provider: 'B', endpoint: 'https://b.test/search', paidExecutionObserved: true, outcomeScored: true, benchmarkFingerprint: 'fp-1', providerCanonicalKey: 'b.test|0xbbb' }]); assert.equal(ranking.rankingReady, true); assert.deepEqual(ranking.comparableFingerprints, ['fp-1']); });
test('different fingerprints cannot be compared', () => { const ranking = rankingReadiness([{ ...base, provider: 'A', paidExecutionObserved: true, outcomeScored: true, benchmarkFingerprint: 'fp-1', providerCanonicalKey: 'a.test|0xaaa' }, { ...base, provider: 'B', endpoint: 'https://b.test/search', paidExecutionObserved: true, outcomeScored: true, benchmarkFingerprint: 'fp-2', providerCanonicalKey: 'b.test|0xbbb' }]); assert.equal(ranking.rankingReady, false); });
test('two brand aliases for the same canonical seller cannot create a ranking', () => { const ranking = rankingReadiness([{ ...base, provider: 'Brand A', paidExecutionObserved: true, outcomeScored: true, benchmarkFingerprint: 'fp-1', providerCanonicalKey: 'shared.test|0xabc' }, { ...base, provider: 'Brand B', endpoint: 'https://shared.test/alternate', paidExecutionObserved: true, outcomeScored: true, benchmarkFingerprint: 'fp-1', providerCanonicalKey: 'shared.test|0xabc' }]); assert.equal(ranking.rankingReady, false); });
test('scored providers without canonical identity do not count toward ranking readiness', () => { const ranking = rankingReadiness([{ ...base, provider: 'A', paidExecutionObserved: true, outcomeScored: true, benchmarkFingerprint: 'fp-1' }, { ...base, provider: 'B', endpoint: 'https://b.test/search', paidExecutionObserved: true, outcomeScored: true, benchmarkFingerprint: 'fp-1' }]); assert.equal(ranking.rankingReady, false); assert.equal(ranking.canonicallyIdentifiedScoredProviders, 0); });
test('canonical identity can be derived from observed recipient plus endpoint host', () => { assert.equal(canonicalProviderIdentity({ endpoint: 'https://Provider.Test/search', paymentRecipientObserved: '0xAbC' }), 'provider.test|0xabc'); });
test('http prefix lookalike is not executable', () => { assert.equal(isExecutableHttpEndpoint('httpx://provider.test'), false); assert.equal(isExecutableHttpEndpoint('https://provider.example/search'), false); assert.equal(isExecutableHttpEndpoint('https://provider.test/search'), true); });
